services:
  prl-devops-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: prl-devops-ui:latest
    container_name: prl-devops-ui
    ports:
      - "5780:80"
    environment:
      APP_ENV: ${APP_ENV:-production}
      VITE_DEFAULT_HOST_URL: ${VITE_DEFAULT_HOST_URL:-}
      VITE_DEFAULT_HOST_NAME: ${VITE_DEFAULT_HOST_NAME:-}
      VITE_DEFAULT_USERNAME: ${VITE_DEFAULT_USERNAME:-}
      VITE_DEFAULT_PASSWORD: ${VITE_DEFAULT_PASSWORD:-}
    restart: unless-stopped

  prl-devops-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: prl-devops-ui:latest
    container_name: prl-devops-ui-dev
    ports:
      - "8081:80"
    environment:
      APP_ENV: development
      VITE_DEFAULT_HOST_URL: ${VITE_DEFAULT_HOST_URL:-}
      VITE_DEFAULT_HOST_NAME: ${VITE_DEFAULT_HOST_NAME:-}
      VITE_DEFAULT_USERNAME: ${VITE_DEFAULT_USERNAME:-}
      VITE_DEFAULT_PASSWORD: ${VITE_DEFAULT_PASSWORD:-}
    restart: unless-stopped
    profiles:
      - dev
