services:
  prl-devops-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prl-devops-ui-dev
    ports:
      - "8081:80"
    environment:
      APP_ENV: development
      VITE_DEFAULT_HOST_URL: ${VITE_DEFAULT_HOST_URL:-}
      VITE_DEFAULT_HOST_NAME: ${VITE_DEFAULT_HOST_NAME:-}
      VITE_DEFAULT_USERNAME: ${VITE_DEFAULT_USERNAME:-}
      VITE_DEFAULT_PASSWORD: ${VITE_DEFAULT_PASSWORD:-}
      ALLOW_INSECURE_STORAGE: ${ALLOW_INSECURE_STORAGE:-true}
    restart: unless-stopped
