apiVersion: v1
kind: Service
metadata:
  name: { { include "prl-devops-ui.fullname" . } }
  labels: { { - include "prl-devops-ui.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "prl-devops-ui.selectorLabels" . | nindent 4 } }
