---
name: Bug report
description: Create a bug report
title: "[BUG] "
labels:
  - bug
  - triage
type: bug
projects:
  - "Parallels/6"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: The module where you encountered the issue.
      options:
        - label: All
          value: all
        - label: Frontend (UI)
          value: frontend
        - label: Backend (API/Service)
          value: backend
        - label: Database/Storage
          value: db
        - label: Build/Deployment
          value: build
  - type: input
    attributes:
      label: Version
      description: The version of the module where you encountered the issue.
      placeholder: e.g. 0.0.0, 0.1.0, 0.1.1
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
        Enable debug logging, when running it by setting the environment variable LOG_LEVEL.
      render: Shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to reproduce the issue.
        To speed up the triaging of your request, reproduce the issue running
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: Yes, I've included all of the above information (Version, settings, logs, etc.)
          required: true
